name: ex03_example
description: A sample command-line application
#dependencies :
#  unittest : any

name: ex03_example
version: 0.0.1
author: Mohamed Bouanane
description: An example how to use ex03 , a library for print.
homepage: http://ondart.me/
dependencies:
  ex03:
      git: git://github.com/bmohamed/ex03.git

  
